name: listfiles after checkout
on: workflow_dispatch

jobs:
  # Build job. Builds app for Android with Buildozer
  list-files:
    name: listfiles after checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list dirs github workspace
        if: ${{ always() }}
        run: |
            echo "::warning::this is a warning"
            find /github/workspace/ -maxdepth 3 -type d
    
      - name: list files cwd
        if: ${{ always() }}
        run: |
            echo "::warning::this is a 2nd warning"
            find . -maxdepth 3

      - name: list dirs runner home
        if: ${{ always() }}
        run: |
            echo "::warning::this is a 3nd warning"
            echo "cwd is $GITHUB_WORKSPACE"
            find $GITHUB_WORKSPACE -maxdepth 3 -type d
